apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zmlwz2zrz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:45be3e71b76fd595eb959314483b3e72f7a1082f@sha256:cf1cdf6bab370eee498815659b56fe05b34c2bcd14ca2f558ac72343fda3f145
          name: container-image
